### ISSUE TITLE
min value problem

### ISSUE THREAD

**Issue by NewInGit** [ncou/jquery.stepper.basic#2]
This is my initialization:
$('#stepper').stepper({
	unit: 's',
	initialValue: 0,
	min: 0,
	max: 300,
	stepSize: 1
});

when I open the page the value inside the input box is : 300s
Why it is not 0 ?

**Comment by ncou** [comment]
Hi,

There is bug, i will do a correction this weekend.

**Comment by ncou** [comment]
Hi,

The correction is made.
Let me know if it's ok for you.
